application: til-newtab
version: 1
runtime: go
api_version: go1

handlers:
- url: /get_random_til
  script: _go_app
- url: /get_random_img
  script: _go_app
- url: /get_all_img
  script: _go_app
- url: /update_saved_posts
  login: admin
  script: _go_app
